name: Build LaTeX document

on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
        - name: Set up Git repository
          uses: actions/checkout@v3
        - name: Compile LaTeX document
          uses: xu-cheng/latex-action@v3
          with:
            root_file: OptimizationMethods.tex
        - name: Upload PDF file
          uses: actions/upload-artifact@v3
          with:
            path: OptimizationMethods.pdf
        - name: Generate release tag
          id: generate_release_tag
          uses: amitsingh-007/next-release-tag@v5.0.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            tag_prefix: 'v'
            tag_template: 'yyyy.mm.dd.i'
        - name: Create github release
          uses: softprops/action-gh-release@v1
          with:
            files: OptimizationMethods.pdf
            tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
            name: Abstract release
            body: |
                New abstract release
            draft: false
            prerelease: false
                